final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("checkout.urls", namespace="checkout")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("payments/", include("payment.urls", namespace="payment"))
]

handler404 = 'checkout.views.error404'

payment/urls.py
from django.urls import path

from . import views

app_name = "payment"

urlpatterns = [
    path("", views.index, name="index"),
    path("add_payment", views.add, name="add"),
    path("delete_payment", views.delete, name="delete")
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = "wishlist"

urlpatterns = [
    path("", views.index, name="index"),
    path("get_wishlist_form", views.get_form, name="get_wishlist_form"),
    path("add", views.add_wishlist, name="add_wishlist"),
    path("delete", views.delete_wishlist, name="delete_wishlist")
]

wishlist/models.py
from django.db import models
from django.core.validators import MinValueValidator
from datetime import datetime
from checkout.models import User

# Create your models here.

class Wishlist(models.Model):
    name = models.CharField(max_length=128)
    price = models.FloatField(validators=[MinValueValidator(0)])
    link = models.CharField(max_length=512, null=True, blank=True)
    date = models.DateField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="wishlist")

    def __str__(self):
        return f"{self.name} - {self.user}"

wishlist/forms.py
from django.forms import ModelForm
from .models import Wishlist
from django import forms


class DateInput(forms.DateInput):
    input_type = 'date'


class WishlistForm(forms.ModelForm):
    class Meta:
        model = Wishlist
        fields = '__all__'
        exclude = ('user', 'date')
        widgets = {
            'date': DateInput(),
        }

wishlist/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Wishlist
from .forms import WishlistForm
import json
from checkout.utils import paginate

# Create your views here.

def index(request):
    items = request.user.wishlist.order_by("-date")
    num = request.GET.get("page", 1)
    items_paginator = paginate(items, num)
    return render(request, "wishlist/index.html", 
                {"paginator": items_paginator["paginator"],
                "page_obj": items_paginator["page_obj"],
                "items": items_paginator["items"]})


@csrf_exempt
def get_form(request):
    form = WishlistForm()
    return render(request, "wishlist/form.html", {"form": form})


def add_wishlist(request):
    data = json.loads(request.body)
    form = WishlistForm(data)
    if form.is_valid():
        item = Wishlist(user=request.user,
                        name=form.cleaned_data["name"],
                        price=form.cleaned_data["price"],
                        link=form.cleaned_data["link"])
        item.save()
        return JsonResponse({"message": "Wishlist item created successfully."}, status=201)
    return JsonResponse({"message": "Invalid form submission."})


def delete_wishlist(request):
    item_id = json.loads(request.body)["item_id"]
    try:
        item = Wishlist.objects.get(id=item_id, user=request.user)
        item.delete()
        return JsonResponse({"message": "Wishlist item deleted"}, status=201)
    except:
        return JsonResponse({"message": "Error."})

wishlist/templates/wishlist/form.html
{% load crispy_forms_tags %}


<form action="{% url 'wishlist:add_wishlist' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-2">Save</button>
</form>

wishlist/templates/wishlist/index.html
{% extends 'checkout/layout.html' %}
{% load static %}

{% block body %}
<button type="submit" class="btn btn-primary" id="add_wishlist">Add To Wishlist</button>

<div id="form" class="container"></div>
<div id="items" class="mt-2 mb-2">
    {% for item in items %}
        <div class="card mt-2 mb-2 item_div" id="{{ item.id }}">
          <div class="card-body card-text">
            Name: {{ item.name }}
            <br>
            Price: ${{ item.price }}
            <br>
            Date: {{ item.date }}
            <br>
            <a href="{{ item.link }}" target="_blank">Link</a>
            <br>
            <button type="submit" class="btn btn-danger delete_wishlist_button">Delete</button>
          </div>
        </div>
    {% endfor %}
</div>
{% if page_obj %}
    <nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
    {% endif %}
    {% for num in paginator.page_range %}
        {% if num == page_obj.number %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Next</a></li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
    {% endif %}
  </ul>
    </nav>
{% else %}
    <h1>No items.</h1>
{% endif %}
{% endblock %}

{% block script %}
    <script src="{% static 'wishlist/addwishlist.js' %}" type="text/javascript"></script>
    <script src="{% static 'wishlist/deletewishlist.js' %}" type="text/javascript"></script>
{% endblock script %}