checkout/urls.py
from django.urls import path

from . import views

app_name = "checkout"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_item", views.create_item, name="create_item"),
    path("profile", views.profile, name="profile"),
    path("edit_item/<int:item_id>", views.edit_item, name="edit_item"),
    path("delete_item", views.delete_item, name="delete_item"),
    path("update_balance", views.update_balance, name="update_balance"),
    path("search", views.search, name="search"),
    path("search/<str:q>", views.search_page, name="search_page"),
    path("categories/<str:name>", views.category, name="category"),
    path("change_password", views.change_password, name="change_password")
]

final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("checkout.urls", namespace="checkout")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("payments/", include("payment.urls", namespace="payment"))
]

handler404 = 'checkout.views.error404'

payment/urls.py
from django.urls import path

from . import views

app_name = "payment"

urlpatterns = [
    path("", views.index, name="index"),
    path("add_payment", views.add, name="add"),
    path("delete_payment", views.delete, name="delete")
]

checkout/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import AbstractUser
from datetime import datetime

# Create your models here.

class User(AbstractUser):
    balance = models.FloatField()

class Category(models.Model):
    name = models.CharField(max_length=64, default="None")
    def __str__(self):
        return self.name.title()

class Item(models.Model):
    name = models.CharField(max_length=128)
    price = models.FloatField(validators=[MinValueValidator(0)])
    quantity = models.IntegerField(validators=[MinValueValidator(1)])
    seller = models.CharField(max_length=64, null=True)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL)
    comment = models.TextField(blank=True, null=True)
    date = models.DateField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="items")

    def __str__(self):
        return f"{self.name} - {self.user}"

checkout/forms.py
from django.forms import ModelForm
from .models import Item
from django import forms
from datetime import datetime


class DateInput(forms.DateInput):
    input_type = 'date'

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        exclude = ('user', 'category')
        widgets = {
            'date': DateInput(),
        }
    category = forms.CharField(required=False)
    field_order = ["name", "price", "quantity", "seller", "date", "category", "comment"]

checkout/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.urls import reverse
from django import forms
from .models import User, Item, Category
from .forms import ItemForm
from .utils import paginate, error, get_categories
import json
from django.db.models import Q, Sum


# Create your views here.

@login_required
def index(request):
    if not request.user.is_authenticated:
        return render(request, "checkout/login.html")
    items = Item.objects.filter(user=request.user).order_by("-date", "-id")
    num = request.GET.get("page", 1)
    items_paginator = paginate(items, num)
    return render(request, "checkout/index.html", 
                {"paginator": items_paginator["paginator"],
                "page_obj": items_paginator["page_obj"],
                "items": items_paginator["items"],
                "categories": get_categories(request.user),
                "items_count": items.count(),
                "items_sum": items.aggregate(Sum("price"))["price__sum"] if items else 0,
                "form": ItemForm()})

@login_required
def create_item(request):
    if request.method == "GET":
        form = ItemForm()
        return render(request, "checkout/new_item.html", {"form": form})

    data = json.loads(request.body)
    form = ItemForm(data)
    if form.is_valid():
        category = data["category"]
        if not category:
            category = "None"
        item_instance = form.save(commit=False)
        category, created = Category.objects.get_or_create(name=category.lower())
        item_instance.category = category
        item_instance.user = request.user
        request.user.balance -= float(form.cleaned_data["price"])
        item_instance.save()
        request.user.save()
        #messages.success(request, "Item created successfully.")
        #return HttpResponseRedirect(reverse("checkout:view_item", kwargs={"item_id": item_instance.id}))
        return JsonResponse({"message": "Item created successfully"}, status=201)
    else:
        #print(form.cleaned_data)
        return JsonResponse({"message": "Error"})

@login_required
def edit_item(request, item_id):
    if request.method == "GET":
        try:
            item = Item.objects.get(id=item_id, user=request.user)
            form = ItemForm(instance=item, initial={"category": item.category})
            return render(request, "checkout/edit_item_form.html", {"form": form, "item_id": item_id})
        except:
            return error(request, "Item not found.")
    else:
        form = ItemForm(request.POST)
        item = Item.objects.get(id=item_id, user=request.user)
        old_price = item.price
        item.name = form.data["name"]
        item.price = form.data["price"]
        item.quantity = form.data["quantity"]
        item.date = form.data["date"]
        item.comment = form.data["comment"]
        if not request.POST["category"]:
            category = "None"
        else:
            category = request.POST["category"]
        c, created = Category.objects.get_or_create(name=category.lower())
        item.category = c
        request.user.balance += old_price - float(item.price)
        item.save()
        request.user.save()
        return JsonResponse({"message": "Item updated"}, status=201)
    
@login_required
def delete_item(request):
    item_id = json.loads(request.body)["item_id"]
    try:
        item = Item.objects.get(id=item_id, user=request.user)
        request.user.balance += item.price
        request.user.save()
        item.delete()
        return JsonResponse({"message": "Item deleted"}, status=201)
    except:
        return JsonResponse({"message": "Error"})

@login_required
def update_balance(request):
    new_balance = json.loads(request.body)["new_balance"]
    request.user.balance = new_balance
    request.user.save()
    return JsonResponse({"message": "Balance updated."}, status=201)

@login_required
def profile(request):
    return render(request, "checkout/profile.html")

@login_required
def search_page(request, q):
    if q is None:
        return error(request, "Query not provided")
    try:
        q = q.lower()
        category = Category.objects.get(name__icontains=q)
    except:
        category = None
    results = request.user.items.filter(Q(name__icontains=q)
                                |Q(price__icontains=q)
                                |Q(quantity__icontains=q)
                                |Q(seller__icontains=q)
                                |Q(category=category)
                                |Q(comment__icontains=q)
                                |Q(date__icontains=q)).order_by("-date")
    num = request.GET.get("page", 1)
    items_paginator = paginate(results, num)
    return render(request, "checkout/paginator.html", 
                {"paginator": items_paginator["paginator"],
                "page_obj": items_paginator["page_obj"],
                "items": items_paginator["items"]})

@login_required
def search(request):
    q = request.GET.get("q", None)
    return HttpResponseRedirect(reverse('checkout:search_page',kwargs={'q': q}))   
 
@login_required
def category(request, name):
    try:
        cat = Category.objects.get(name=name.lower())
    except:
        return error(request, "Category doesn't exist.")
    items = cat.item_set.filter(user=request.user)
    num = request.GET.get("page", 1)
    items_paginator = paginate(items, num)
    return render(request, "checkout/index.html", 
                {"paginator": items_paginator["paginator"],
                "page_obj": items_paginator["page_obj"],
                "items": items_paginator["items"],
                "categories": get_categories(request.user),
                "items_count": request.user.items.count(),
                "items_sum": request.user.items.aggregate(Sum("price"))["price__sum"] if items else 0})

@login_required
def change_password(request):
    old_password = request.POST["old_password"]
    new_password = request.POST["new_password"]
    if request.user.check_password(old_password):
        request.user.set_password(new_password)
        request.user.save()
        login(request, request.user)
        messages.success(request, "Password updated successfully.")
        #return render(request, "checkout/profile.html")
        return HttpResponseRedirect(reverse("checkout:profile"))
    else:
        return error(request, "Wrong password. Please try again.")
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("checkout:index"))
        else:
            return render(request, "checkout/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "checkout/login.html")

@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("checkout:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "checkout/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password, balance=request.POST["balance"])
            user.save()
        except IntegrityError:
            return render(request, "checkout/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("checkout:index"))
    else:
        return render(request, "checkout/register.html")

def error404(request, exception):
    return error(request, "Error 404. Page not found.")

checkout/templates/checkout/edit_item_form.html
{% load crispy_forms_tags %}

<div class="m-4 p-4">
    {{ form|crispy }}
    <input type="hidden" name="item_id" value="{{ item_id }}">
    <button type="submit" class="btn btn-primary mt-2">Save</button>
</div>

checkout/templates/checkout/error.html
{% extends "checkout/layout.html" %}

{% block body %}
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Error!</h4>
        <p>{{ message }}</p>
    </div>
{% endblock %}

checkout/templates/checkout/index.html
{% extends "checkout/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
    <h2 id="balance" style="display: inline-block">Balance: ${{ user.balance }}</h2>
    {% if form %}
        <button type="submit" class="btn btn-primary mb-4" id="new_item_button">Add Item</button>
    {% endif %}
    <ul class="list-group">
        <li class="list-group-item"><a href="{% url 'checkout:index' %}">All - {{ items_count }} items - ${{ items_sum }}
        </a></li>
        {% for category in categories %}
            <li class="list-group-item"><a href="{% url 'checkout:category' category.title|lower %}">
                {{ category.title }} - {{ category.count}} items - ${{ category.sum }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% if form %}
<form action="{% url 'checkout:create_item' %}" id="new_item_form"  style="display:none" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endif %}

<div id="items_list">
{% for item in items %}

    <div class="card mt-4 mb-4 item_div" id="{{ item.id }}">
      <div class="card-body">
        <h2 class="card-title"><span class="item item_name">{{ item.name }}</span></h2>
        <p class="card-text p-4">
        Price: $<span class="item item_price">{{ item.price }}</span>
        <br>
        Quantity: <span class="item item_quantity">{{ item.quantity }}</span>
        <br>
        Seller: <span class="item item_seller">{{ item.seller }}</span>
        <br>
        Date: <span class="item item_date">{{ item.date }}</span>
        <br>
        Category: <span class="item item_category">{{ item.category }}</span>
        <br>
        {% if item.comment %}
        Comment: 
        {% endif %}
        <span class="item item_comment">{{ item.comment }}</span>
        </p>
        <button type="submit" class="btn btn-primary edit_button">Edit</button>
        <button type="submit" class="btn btn-danger delete_button">Delete</button>
      </div>
    </div>

{% endfor %}
</div>
{% if page_obj %}
    <nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
    {% endif %}
    {% for num in paginator.page_range %}
        {% if num == page_obj.number %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Next</a></li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
    {% endif %}
  </ul>
    </nav>
{% else %}
    <h1>No items.</h1>
{% endif %}
{% endblock %}

{% block script %}
<script src="{% static 'checkout/add_item.js' %}"></script>
{% endblock script %}

checkout/templates/checkout/layout.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Checkout{% endblock %}</title>
        <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        -->
        <link href="{% static 'checkout/styles.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'checkout/darkly.css' %}" rel="stylesheet" type="text/css">
        <link rel="shortcut icon" type="image/png" href="{% static 'checkout/logo.png' %}">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4 sticky-top">
            <a class="navbar-brand" href="{% url 'checkout:index' %}"><img style="height: 35px; width: 35px" src="{% static 'checkout/logo.png' %}"><strong> Checkout</strong></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'payment:index' %}">Payments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'wishlist:index' %}">Wishlist</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'checkout:profile' %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
            
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'checkout:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'checkout:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'checkout:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
              {% if user.is_authenticated %}
                <form action="{% url 'checkout:search' %}" method="GET" class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                </form>
              {% endif %}
            </div>
          </nav>
        
        {% if messages %}
            {% for message in messages %}
                {% if message.tags %}
                        <div class="alert alert-{{ message.tags }}" role="alert">
                            <p>{{ message }}</p>
                        </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% block extra %} {% endblock %}
        <div class="body container">
            {% block body %}
            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        <script src="{% static 'checkout/edit_item.js' %}" type="text/javascript"></script>
        <script src="{% static 'checkout/delete_item.js' %}" type="text/javascript"></script>
        {% block script %}
        {% endblock  %}
        
    </body>
</html>

checkout/templates/checkout/login.html
{% extends "checkout/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'checkout:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'checkout:register' %}">Register here.</a>

{% endblock %}

checkout/templates/checkout/paginator.html
{% extends "checkout/layout.html" %}

{% block body %}

{% for item in items %}

    <div class="card m-4 item_div" id="{{ item.id }}">
      <div class="card-body">
        <h2 class="card-title"><span class="item item_name">{{ item.name }}</span></h2>
        <p class="card-text p-4">
        Price: $<span class="item item_price">{{ item.price }}</span>
        <br>
        Quantity: <span class="item item_quantity">{{ item.quantity }}</span>
        <br>
        Seller: <span class="item item_seller">{{ item.seller }}</span>
        <br>
        Date: <span class="item item_date">{{ item.date }}</span>
        <br>
        Category: <span class="item item_category">{{ item.category }}</span>
        <br>
        {% if item.comment %}
        Comment: 
        {% endif %}
        <span class="item item_comment">{{ item.comment }}</span>
        </p>
        <button type="submit" class="btn btn-primary edit_button">Edit</button>
        <button type="submit" class="btn btn-danger delete_button">Delete</button>
      </div>
    </div>

{% endfor %}

{% if page_obj %}
    <nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
    {% endif %}
    {% for num in paginator.page_range %}
        {% if num == page_obj.number %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Next</a></li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
    {% endif %}
  </ul>
    </nav>
{% else %}
    <h1>No items.</h1>
{% endif %}
{% endblock %}

checkout/templates/checkout/profile.html
{% extends "checkout/layout.html" %}
{% load static %}

{% block body %}
    <div class="jumbotron jumbotron-fluid text-center">
        <div class="container">
          <h1 class="display-4">{{ request.user.username }}</h1>
          <p class="lead">Email: {{ request.user.email }}
          <br>
          Created on: {{ request.user.date_joined }}
          <br>
          Balance: $<span id="balance">{{ request.user.balance }}</span>
          <br>
          <button type="submit" id="update" class="btn btn-primary">Update</button>
          <br>
          (Doesn't affect payments)
          <br>
          Items: {{ request.user.items.count }}
        </div>
        <form action="{% url 'checkout:change_password' %}" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label>Old password</label>
            <input type="password" class="form-control" style="width: 25%; margin: auto" name="old_password">
            <label>New password</label>
            <input type="password" class="form-control" style="width: 25%; margin: auto" name="new_password">
          </div>
          <button class="btn btn-primary">Change</button>
    </div>
{% endblock %}

{% block script %}
  <script>
    document.querySelector("#update").onclick = () => {
        let new_balance = prompt("Enter new balance");
        if (new_balance != null) {
          new_balance = parseFloat(new_balance);
          if (isNaN(new_balance))
            alert("Invalid number");
          else {
            console.log(new_balance);
            const request = new Request("/update_balance", 
              {headers: {'X-CSRFToken': getCookie("csrftoken")}});
            fetch(request, {
              method: "POST",
              body: JSON.stringify({
                    new_balance: new_balance
                })
              }
            )
            .then(response => response.json())
            .then(result => {
              console.log(result);
              document.querySelector("#balance").textContent = new_balance;
            });
            

          }
        }
      }
  </script>
{% endblock  %}

checkout/templates/checkout/register.html
{% extends "checkout/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'checkout:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="number" name="balance" placeholder="Balance">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'checkout:login' %}">Log In here.</a>

{% endblock %}

checkout/templates/checkout/search.html
{% extends "checkout/layout.html" %}

{% block body %}

<form action="{% url 'checkout:search' %}" method="GET">
    {% csrf_token %}
    <input type="input" class="form-control" name="q">

</form>

<div>
    {{ results }}
</div>

{% endblock %}