final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("checkout.urls", namespace="checkout")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("wishlist/", include("wishlist.urls", namespace="wishlist")),
    path("payments/", include("payment.urls", namespace="payment"))
]

handler404 = 'checkout.views.error404'

payment/urls.py
from django.urls import path

from . import views

app_name = "payment"

urlpatterns = [
    path("", views.index, name="index"),
    path("add_payment", views.add, name="add"),
    path("delete_payment", views.delete, name="delete")
]

payment/models.py
from django.db import models
from django.core.validators import MinValueValidator
from datetime import datetime
from checkout.models import User

# Create your models here.

class Payment(models.Model):
    source = models.CharField(max_length=64)
    value = models.FloatField(validators=[MinValueValidator(0)])
    date = models.DateField(default=datetime.now)
    user = models.ForeignKey(User, on_delete=models.PROTECT, related_name="payments")

    def __str__(self):
        return f"{self.source} - {self.value} - {self.date}"

payment/forms.py
from django import forms
from .models import Payment

class DateInput(forms.DateInput):
    input_type = 'date'

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = '__all__'
        exclude = ('user', )
        widgets = {
            'date': DateInput(),
        }

    field_order = ["value", "source", "date"]

payment/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import Payment
from .forms import PaymentForm
from checkout.utils import paginate
import json
from django.db.models import Sum


# Create your views here.

def index(request):
    payments = Payment.objects.filter(user=request.user).order_by("-date", "-id")
    num = request.GET.get("page", 1)
    payments_paginator = paginate(payments, num)
    return render(request, "payment/index.html", 
                {"paginator": payments_paginator["paginator"],
                "page_obj": payments_paginator["page_obj"],
                "payments": payments_paginator["items"],
                "form": PaymentForm(),
                "payments_sum": payments.values("value").aggregate(Sum('value'))["value__sum"] if payments else 0})


def add(request):
    if request.method == "POST":
        form = PaymentForm(json.loads(request.body))
        if form.is_valid():
            payment = Payment(user=request.user,
                            source=form.cleaned_data["source"],
                            value=form.cleaned_data["value"],
                            date=form.cleaned_data["date"])
            payment.save()
            request.user.balance += form.cleaned_data["value"]
            request.user.save()
        return JsonResponse({"message": "Payment added"}, status=201)

def delete(request):
    payment_id = json.loads(request.body)["payment_id"]
    payment = Payment.objects.get(user=request.user, id=payment_id)
    request.user.balance -= payment.value
    payment.delete()
    request.user.save()
    return JsonResponse({"message": "Payment deleted"}, status=201)

payment/templates/payment/index.html
{% extends 'checkout/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}

<form action="{% url 'payment:add' %}" method="POST" id="payment_form">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mt-2 mb-2">Add</button>
</form>

<h2>${{ payments_sum }}</h2>
<div id="payments_list">
{% for payment in payments %}
    <div class="card mb-2 item_div" id="{{ payment.id }}">
      <div class="card-body">
        <h2 class="card-title">${{ payment.value }}</h2>
        <p class="card-text">
        Source: {{ payment.source }}
        <br>
        Date: {{ payment.date }}
        </p>
        <a href="#" class="btn btn-danger payment_delete_button">Delete</a>
      </div>
    </div>
{% endfor %}
</div>

{% if page_obj %}
    <nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
    {% endif %}
    {% for num in paginator.page_range %}
        {% if num == page_obj.number %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Next</a></li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
    {% endif %}
  </ul>
    </nav>
{% else %}
    <h1>No payments.</h1>
{% endif %}
{% endblock body %}

{% block script %}
<script src="{% static 'payment/add_payment.js' %}" type="text/javascript"></script>
<script src="{% static 'payment/delete_payment.js' %}" type="text/javascript"></script>
{% endblock script %}